<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * @var $block \Qianrui\Order\Block\Adminhtml\Items\Column\Name
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $block->getData('catalogHelper');
?>
<?php if ($_item = $block->getItem()): ?>
    <div id="order_item_<?= (int) $_item->getId() ?>_title"
         class="product-title">
        <?= $block->escapeHtml($_item->getName()) ?>
    </div>
    <div class="product-sku-block">
        <span><?= $block->escapeHtml(__('SKU'))?>:</span>
        <?= /* @noEscape */ implode('<br />', $catalogHelper->splitSku($block->escapeHtml($block->getSku()))) ?>
    </div>

    <?php if ($block->getOrderOptions()): ?>
        <dl class="item-options">
            <?php foreach ($block->getOrderOptions() as $_option): ?>
                <dt><?= $block->escapeHtml($_option['label']) ?>:</dt>
                <dd>
                    <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                        <?= /* @noEscape */ $block->getCustomizedOptionValue($_option) ?>
                    <?php else: ?>
                        <?php $_option = $block->getFormattedOption($_option['value']); ?>
                        <?php $dots = 'dots' . uniqid(); ?>
                        <?php $id = 'id' . uniqid(); ?>
                        <?= $block->escapeHtml($_option['value'], ['a', 'br']) ?>
                        <?php if (isset($_option['remainder']) && $_option['remainder']): ?>
                            <span id="<?= /* @noEscape */ $dots; ?>"> ...</span>
                            <span id="<?= /* @noEscape */ $id; ?>">
                                <?= $block->escapeHtml($_option['remainder'], ['a']) ?>
                            </span>
                            <?php $scriptString = <<<script
                                require(['prototype'], function() {

script;
                            $scriptString .= "$('" . /* @noEscape */ $id . "').hide();" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $id . "').show();});" .
                                PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $dots .
                                "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $id .
                                "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $dots .
                                "').show();});" . PHP_EOL . "});" . PHP_EOL;
                            ?>
                            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?= $block->escapeHtml($_item->getDescription()) ?>

    <?php
    $imeis = $block->getImeis();
    if(1):
        $isAllow = $block->isAllowed('Magento_Sales::update_imei');
    ?>
        <div class="product-imei">
            <a href="javascript:void(0)" id="popup-imei-<?= $_item->getId() ?>"><?= __('IMEI') ?></a>
            <div class="no-display" data-mage-init='{
                "Magento_Ui/js/modal/modal":{
                        "trigger": "#popup-imei-<?php echo $_item->getId(); ?>",
                        "title": "<?= $block->escapeHtml(__('IMEI')) ?>"
                    }
                }'>
                <table class="data-table admin__table-secondary">
                    <?php foreach ($imeis as $imei): ?>
                        <tr>
                            <td class="imei"><?= $imei ?></td>
                            <?php if($isAllow): ?>
                                <td><button type="button" class="delete"><span>Delete</span></button></td>
                            <?php endif; ?>
                        </tr>
                    <?php endforeach; ?>
                    <?php if($isAllow): ?>
                        <tr>
                            <td><input type="text" value="" /></td>
                            <td>
                                <button type="button" id="add"><span>Add</span></button>
                                <button type="button" id="save"><span>Save</span></button>
                                <span class="product-imei-tips"></span>
                            </td>
                        </tr>
                    <?php endif; ?>
                </table>
            </div>
        </div>
        <style type="text/css">
            .product-imei {
                margin: 1rem 0 0;
            }

            .product-imei-tips {
                color: #185b00
            }
        </style>
        <script type="text/javascript">
            require([
                'jquery',
                'Magento_Ui/js/modal/confirm'
            ], function ($, confirm){
                $('.data-table').on('click', '.delete', function(){
                    $(this).parent().parent().remove();
                });
                $('#add').on('click', function(){
                    let imei = $(this).parent().siblings().find('input').val()
                    if(imei!=''){
                        let tr = '<tr><td class="imei">' + imei + '</td>' +
                            '<td><button type="button" class="delete"><span>Delete</span></button></td></tr>';
                        $(this).parent().parent().before(tr);
                        $(this).parent().siblings().find('input').val('');
                    }
                });
                $('#save').on('click', function(){
                    let imei = [];
                    $('.imei').each(function(){
                        imei.push($(this).html())
                    });

                    confirm({
                        'content': 'Are you sure to update product serial?',
                        'actions': {
                            confirm: function () {
                                $.ajax({
                                    url: '<?= $block->getUrl('order/imei/save'); ?>',
                                    type: 'post',
                                    data: {
                                        'item_id': <?= $_item->getItemId(); ?>,
                                        'imei': imei.join(",")
                                    },
                                    showLoader: true
                                }).done(function (result) {
                                    if(result.code==0) {
                                        $('.product-imei-tips').html(result.message);
                                        window.location.reload();
                                    }else{
                                        alert(result.message);
                                    }
                                });
                            }
                        }
                    });
                });
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
